# Generated by Django 5.0.6 on 2026-09-23 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('pack', 'Pack'), ('box', 'Box')], default='kg', max_length=10)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_nugget', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telepon', 'Telepon'), ('walk_in', 'Datang Langsung')], default='whatsapp', max_length=20)),
                ('wa_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Timbang'), ('ditimbang', 'Sudah Ditimbang'), ('nota', 'Nota Dibuat'), ('batal', 'Batal')], default='menunggu', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='orders.customer')),
                ('input_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_as_admin', to=settings.AUTH_USER_MODEL)),
                ('marketing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests_as_marketing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_weighed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.product')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.productrequest')),
            ],
        ),
    ]
